name: Deploy OPML to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4

    - name: Run OPML generation script
      run: python transform_to_opml.py

    - name: List OPML files
      run: ls *.opml > opml_files.txt

    - name: Generate URLs
      run: |
        REPO_NAME=$(basename $GITHUB_REPOSITORY)
        BASE_URL="https://${{ github.actor }}.github.io/${REPO_NAME}"
        while read -r FILE; do
          echo "${BASE_URL}/${FILE}" >> opml_urls.txt
        done < opml_files.txt

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        exclude_assets: |
          .github/**
          README.md
          transform_to_opml.py

    - name: Upload OPML URLs
      uses: actions/upload-artifact@v3
      with:
        name: opml-urls
        path: opml_urls.txt