name: OPML Generator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4

    - name: Run OPML generation script
      run: python transform_to_opml.py

    - name: Upload grouped OPML file
      uses: actions/upload-artifact@v2
      with:
        name: grouped-feeds
        path: grouped_feeds.opml

    - name: Upload individual OPML files
      uses: actions/upload-artifact@v2
      with:
        name: individual-feeds
        path: '*.opml'
        if-no-files-found: error
